### ISSUE TITLE
Milestone

### ISSUE THREAD

**Issue by COD1995** [COD1995/A-Comprehensive-Note-on-Machine-Learning#1]
I planned to finish the following while running my experiment for my research
- [ ] Continual Learning Section
    - [x]  An overview
    - [ ]  Representative Algorithm from each Continual Learning Method
- [x] Notation Chapter
- [ ] Basic Machine Learning Algorithms
